example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist
from mywatchlist.views import show_xml
from mywatchlist.views import show_json 


app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path('xml/', show_xml, name="show_xml"),
    path('json/', show_json, name="show_json")
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls'))
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import create_task, logout_user, register, delete_task, is_finished, is_not_finished, show_json, add_todolist_item
from todolist.views import todolist
from todolist.views import login_user 

app_name = 'todolist'

urlpatterns = [
    path('', todolist, name='todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('<int:id>', delete_task, name = 'delete_task'),
    path('<int:id>/finished', is_finished, name ='finished'),
    path('<int:id>/not-finished', is_not_finished, name='not_finished'),
    path('json/', show_json, name='show_json'),
    path('add/', add_todolist_item, name="add_todolist_item"),
    path('delete/<int:id>', delete_task, name='delete_task')
    
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class MyWatchlistItem(models.Model):
    watched = models.BooleanField()
    title = models.TextField()
    rating = models.IntegerField()
    release_date = models.TextField()
    review = models.TextField()

todolist/models.py
from django.contrib.auth.models import User
from django.db import models

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.TextField()
    description = models.TextField(null = True)
    is_finished = models.BooleanField(default = False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# Create your views here.
def show_katalog(request):
    item_list_catalog = CatalogItem.objects.all()
    context = {
    'item_list': item_list_catalog,
    'nama': 'Ikhlasul Akmal Hanif',
    'npm' : '2106650462',
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render

from mywatchlist.models import MyWatchlistItem
from django.http import HttpResponse
from django.core import serializers

def show_mywatchlist(request):
    item_list_watchlist = MyWatchlistItem.objects.all()
    watched_cnt = 0
    for item in item_list_watchlist:
        if item.watched:
            watched_cnt += 1
    if (watched_cnt*2 >= len(item_list_watchlist)):
        is_watched_cnt = True
    else:
        is_watched_cnt = False
    context = {
    'item_list': item_list_watchlist,
    'nama': 'Ikhlasul Akmal Hanif',
    'npm' : '2106650462',
    'is_watched_cnt' : is_watched_cnt
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data = MyWatchlistItem.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchlistItem.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from todolist.models import Task
from django.contrib.auth.models import User


# Create your views here.
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            response.set_cookie('user', user.id)
            response.set_cookie('username', username)
            return response
    context = {}
    return render(request, 'login.html', context)

@login_required(login_url='/todolist/login/')
def todolist(request):
    data = Task.objects.filter(user = request.COOKIES['user'])
    
    context = { 
        'item_list' : data,
        'last_login' : request.COOKIES['last_login'],
        'user' : request.COOKIES['username']
    }
    return render(request, 'todolist.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == 'POST':
        user_id = request.COOKIES['user']
        date = datetime.datetime.now()
        title = request.POST.get('title')
        description = request.POST.get('description')
        
        Task.objects.create(user = User.objects.get(pk = user_id), date = date, title = title, description = description)
        
        response = HttpResponseRedirect(reverse("todolist:todolist"))
        return response
    context = {}
    return render(request, 'create_task.html', context)

def delete_task(request, id):
    task = Task.objects.get(pk=id)
    task.delete()
    return HttpResponse(b"DELETED", status=201)

def is_finished(request,id):
    task = Task.objects.get(pk=id)
    task.is_finished = True
    task.save()
    response = HttpResponseRedirect(reverse("todolist:todolist"))
    return response

def is_not_finished(request, id):
    task = Task.objects.get(pk=id)
    task.is_finished = False
    task.save()
    response = HttpResponseRedirect(reverse("todolist:todolist"))
    return response

@login_required(login_url='/todolist/login/')
def show_json(request):
    data = Task.objects.filter(user = request.COOKIES['user'])
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/todolist/login/')
def add_todolist_item(request):
    if request.method == 'POST':
        user_id = request.COOKIES['user']
        date = datetime.datetime.now()
        title = request.POST.get('title')
        description = request.POST.get('description')
        
        new_task = Task(user = User.objects.get(pk = user_id), date = date, title = title, description = description)
        new_task.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: {{nama}}</h5>

  <h5>Student ID: {{npm}}</h5>

  <style> 
    .main-table{
      border-collapse: collapse;
      margin : 25px 0;
      font-size : 1.0em;
      min-width: 1400px;
    }
    .main-table th {
      background-color:	rgb(27, 32, 77);
      color: #ffffff;
      text-align: left;
      font-weight: bold;
      
    }

    .main-table th,
    .main-table td{
      padding: 12px 15px;
    }

    .main-table td {
      background-color : #97c3da;
      font-family : sans-serif;
    }
  </style>


  <table class = "main-table">
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in item_list %}
        <tr>
            <td>{{item.item_name}}</td>
            <td>{{item.item_price}}</td>
            <td>{{item.item_stock}}</td>
            <td>{{item.rating}}</td>
            <td>{{item.description}}</td>
            <td>{{item.item_url}}</td>
        </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}



  <h1 class="header">Tugas 3 Assignment PBP</h1>

  <h4 class="header">Name: {{nama}}</h4>

  <h4 class="header">Student ID: {{npm}}</h4>


  <table class = "main-table">
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in item_list %}
        <tr>
            <td>{{item.watched}}</td>
            <td>{{item.title}}</td>
            <td>{{item.rating}}</td>
            <td>{{item.release_date}}</td>
            <td>{{item.review}}</td>
        </tr>
    {% endfor %}
  </table>
  {% if is_watched_cnt %}
    <h5 class="header">Selamat, kamu sudah banyak menonton!</h5>
  {% else %}
    <h5 class="header">Wah, kamu masih sedikit menonton!</h5>
  {% endif %}

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% load static %}
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">    
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create Task</title>
{% endblock meta %}

{% block content %}  

<div class = "create_task">
    <section class="vh-100">
        <div class="container py-5 h-100">
          <div class="row d-flex align-items-center justify-content-center h-100">
            <div class="col-md-8 col-lg-7 col-xl-6">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg"
                class="img-fluid" alt="Phone image">
            </div>
            <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
                <form method="POST" action="">
                    {% csrf_token %}
                    <table>
                        <div class="form-outline mb-4">
                            <label>Title</label>
                            <input type="text" name="title" placeholder="Title" class="form-control">
                        </div>    
                        <div class="form-outline mb-4">
                            <label>Description</label>
                            <input type="text" name="description" placeholder="Description" class="form-control">
                        </div> 
                        
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>

                    </table>
                </form>
      
              </form>
            </div>
          </div>
        </div>
      </section>


    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
  

<div class = "login">

    <section class="vh-100">
        <div class="container py-5 h-100">
          <div class="row d-flex align-items-center justify-content-center h-100">
            <div class="col-md-8 col-lg-7 col-xl-6">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg"
                class="img-fluid" alt="Phone image">
            </div>
            <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
                <form method="POST" action="">
                    {% csrf_token %}
                    <table>
                        <div class="form-outline mb-4">
                            <label>Username</label>
                            <input type="text" name="username" placeholder="Username" class="form-control">
                        </div>    
                        <div class="form-outline mb-4">
                            <label>Username</label>
                            <input type="password" name="password" placeholder="Password" class="form-control">
                        </div> 
                        <div class="d-flex justify-content-around align-items-center mb-4">
                            <div class="form-check">
                              <input class="form-check-input" type="checkbox" value="" checked />
                              <label class="form-check-label"> Remember me </label>
                            </div>
                            <a href="{% url 'todolist:register' %}">Create Account?</a>
                          </div>
                
                        
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Sign in</button>

                    </table>
                </form>
      
              </form>
            </div>
          </div>
        </div>
      </section>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">

        <form method="POST" >  
            {% csrf_token %}
            <section class="vh-100" style="background-color: #2779e2;">
                <div class="container h-100">
                  <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-xl-9">
              
                      <h1 class="text-white mb-4">Create your Account!</h1>
              
                      <div class="card" style="border-radius: 15px;">
                        <div class="card-body">
              
                          <div class="row align-items-center pt-4 pb-3">
                            <div class="col-md-3 ps-5">
              
                              <h6 class="mb-0">Username</h6>
              
                            </div>
                            <div class="col-md-9 pe-5">
              
                              {{form.username}}
              
                            </div>
                          </div>
              
                          <hr class="mx-n3">
              
                          <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">
              
                              <h6 class="mb-0">Password</h6>
              
                            </div>
                            <div class="col-md-9 pe-5">
              
                                {{form.password1}}
              
                            </div>
                          </div>

                          <hr class="mx-n3">
                          
                          <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">
              
                              <h6 class="mb-0">Confirm Password</h6>
              
                            </div>
                            <div class="col-md-9 pe-5">
              
                                {{form.password2}}
              
                            </div>
                          </div>
              
                          <hr class="mx-n3">
              

              
                          <div class="px-5 py-4">
                            <button type="submit" class="btn btn-primary btn-lg">Create Account</button>
                          </div>
              
                        </div>
                      </div>
              
                    </div>
                  </div>
                </div>
              </section> 
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

 {% block content %}
 <style>
  .header{
    text-align: center;
    font-family : sans-serif;
    font-weight: bold;
    font-weight: 200;
  }

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  transition: 0.3s;
  margin: auto;
  margin-bottom: 0.2cm;
}


.card:hover {
  box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.589);
}

.container {
  padding: 2px 16px;
}

.nav.navbar-nav.navbar-right {
    color: white;
}
.header{
    text-align: center;
    font-family : sans-serif;
    margin-top: 0.5cm;
  }

.body{
  background-color: bisque;
}

 </style>

  <head>
    <title>todolist</title>
  </head>
  <nav class="navbar navbar-expand-lg bg-dark">
    <a class = "btn btn-dark" href="{% url 'todolist:logout' %}">Logout</a>
    <a class="btn btn-dark" href="{% url 'todolist:create_task' %}">Tambah Task</a>
  </nav>
  <h4 class="header">Selamat datang {{user}}</h4>
  <div class = "container">
    <div class = "row" id = "task_card">
        
    </div>
  </div>
    

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Add Task
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Add Task</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form id="form" onsubmit="return false;">
          <div class="modal-body">
            {% csrf_token %}
              <table>
                  <div class="form-outline mb-4">
                      <label>Title</label>
                      <input type="text" name="title" placeholder="Title" class="form-control">
                  </div>    
                  <div class="form-outline mb-4">
                      <label>Description</label>
                      <input type="text" name="description" placeholder="Description" class="form-control">
                  </div> 
              </table>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button id="addButton" type="button" class="btn btn-primary">Save changes</button>
          </div>
      </form>
      </div>
  </div>
</div>

<script>
  async function getTask() {
    return fetch("{% url 'todolist:show_json' %}").then((res) => res.json())
  }

  async function refreshTask() {
    console.log("pepe")
    document.getElementById("task_card").innerHTML = ""
    const task = await getTask()
    console.log(task)
    let htmlString = ""
    task.forEach((item) => {
      htmlString += ` 
      <div class="col-12 col-md-6 col-lg-4 col-xxl-3 mx-auto">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="https://img.freepik.com/free-vector/illustration-checklist-clipboard_53876-43946.jpg?w=2000" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">${item.fields.title}</h5>
            <p class="card-text">${item.fields.description}</p>
            <p class="card-text">Sudah dikerjakan : ${Boolean(item.fields.is_finished)}</p>
          </div>
            
          <div class="card-body">
              <a class="btn btn-danger" onclick="deleteTask(${item.pk})">Hapus</a>
          </div>             
          <div class="card-footer">
            ${item.fields.date}
          </div>
        </div>
      </div>`
    })
    document.getElementById("task_card").innerHTML = htmlString
    console.log("pepe2")
  }

  function addTask() {
    fetch("{% url 'todolist:add_todolist_item' %}", {
          method: "POST",
          body: new FormData(document.querySelector('#form'))
      }).then(refreshTask)
    return false
  }

  function deleteTask(id) {
    console.log(id)
    let url = "/todolist/delete/" + id;
    fetch(url).then(refreshTask)
  }

  document.getElementById('addButton').onclick = addTask
  refreshTask()
 
</script>

  <h5>Sesi terakhir login: {{ last_login }}</h5>
 {% endblock content %}